return {
    -- "hrsh7th/nvim-cmp",
    -- event = "InsertEnter",
    -- dependencies = {
    --     "hrsh7th/cmp-buffer",
    --     "hrsh7th/cmp-path",
    -- },
    -- config = function()
    --     require("cmp").setup({
    --         mapping = require("cmp").mapping.preset.insert({
    --             ["<C-k>"] = require("cmp").mapping.select_prev_item(),
    --             ["<C-j>"] = require("cmp").mapping.select_next_item(),
    --             ["<CR>"] = require("cmp").mapping.confirm({select = true}),
    --             ["<C-e>"] = require("cmp").mapping.abort(),
    --         }),
    --         sources = require("cmp").config.sources({
    --             {name = "nvim_lsp"},
    --             {name = "buffer"},
    --             {name = "path"},
    --         }),
    --     })
    -- end,
}
